### ISSUE TITLE
Custom pattern?

### ISSUE THREAD

**Issue by cpursley** [celsodantas/protokoll#22]
Interesting project! Is there way to pass in a pattern dynamically based on an object? For example, each user would set their own increment rules that are passed into the pattern. Some user would want `"CAR%y#####"` while another may need `BOAT-%Y-###`. Does that make sense?

**Comment by cpursley** [comment]
I suppose this is related to https://github.com/celsodantas/protokoll/issues/9

I'd be happy to work on this - do you have any suggestions on an approach?

**Comment by celsodantas** [comment]
Feel free to work on it.

The way the lib works is by creating a table called `custom_auto_increments` and uses the model name to track the increments. One way to do it is to allow a dynamic model name to be set per model instance.

The problem is that to have the increment per object is that you need some sort of the ID for the object, but the DB only returns the object ID once you save it.

```
user = User.new
user.id
# nil
```

You'll need to save the ActiveRecord model first to then generate the auto-increment number, which is a bad solution.

Not sure how to solve this. 
Here is where we set the name into table: https://github.com/celsodantas/protokoll/blob/5e2c89c499e4bd47624217789f0420905724d194/lib/protokoll/counter.rb#L6

If you have any idea how to solve this, feel free to post here so we can discuss a solution.

**Comment by cpursley** [comment]
Thanks for the notes @celsodantas. I ended up going another direction. If I decide to come back and use your gem, I'll look in to this approach. Thanks again; I'm going to go ahead and close this issue for now.
